# Generated by Django 6.0 on 2026-01-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('Fuerza', 'Fuerza'), ('Cardio', 'Cardio'), ('Calistenia', 'Calistenia'), ('Yoga', 'Yoga'), ('Flexibilidad', 'Flexibilidad')], max_length=20),
        ),
    ]
