# Generated by Django 6.0.2 on 2026-02-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ejercicio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='imagen',
            field=models.CharField(blank=True, help_text='Nombre del archivo en /exercises/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='video',
            field=models.CharField(blank=True, help_text='Nombre del archivo en /exercises/', max_length=255, null=True),
        ),
    ]
