# Generated by Django 6.0.2 on 2026-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ejercicio_imagen_ejercicio_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='registroejercicio',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='registroejercicio',
            name='repeticiones',
        ),
        migrations.AddField(
            model_name='registroejercicio',
            name='cantidad',
            field=models.FloatField(default=0, help_text='Repeticiones, minutos o km'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='unidad',
            field=models.CharField(choices=[('reps', 'Repeticiones'), ('minutos', 'Minutos'), ('km', 'Kilómetros')], default='reps', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroejercicio',
            name='peso',
            field=models.FloatField(default=0, help_text='kg'),
        ),
        migrations.AlterField(
            model_name='registroejercicio',
            name='series',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
